# This file is loaded in addition to the regular docker-compose.yml only for the 'machine-name-here' environment; see https://docs.docker.com/compose/extends/#different-environments

version: '3'

services:
  default:
    # This container exists only to supply default values for the other containers to inherit
    # It serves no function in the app itself, and exits immediately on startup
    image: alpine
    entrypoint: ['/bin/sh']
    environment: &default_environment
      #
      # Common across all environments
      #
      # From docker/.env:
      DOCKER_MODE: $DOCKER_MODE
      OBJECTS_ROOT_URL: $OBJECTS_ROOT_URL
      # General
      ADMIN_EMAIL_ADDRESS: noreply@opentext.com
      EMAIL_HOST: smtp.opentext.com
      EMAIL_PORT: 25
      # Docker
      DEPLOY_CUSTOMIZATIONS: 'true' # Include our customizations, or start up an out-of-the-box OpenText Media Management app
      # Postgres
      POSTGRES_SERVER: postgres # Hostname of Postgres server
      POSTGRES_USER: postgres
      #
      # Specific to this environment
      #
      # General
      APP_ROOT_URL: https://machine-name-here.opentext.com
      APP_SERVER: machine-name-here.opentext.com
      DOCKER_MACHINE: machine-name-here
      KEYSTORE_PASSWORD: MediaVault
      # OpenText Media Management
      OTMM_ADMIN_PASSWORD: MediaVault # Password of `tsuper`
      # OpenText Directory Services
      OTDS_ADMIN_PASSWORD: MediaVault1! # Password of `otadmin@otds.admin` user; note that password must contain at least one number and one symbol
      # Postgres
      POSTGRES_PASSWORD: MediaVault # Password of `postgres` user
      DATABASE_USER_PASSWORD: MediaVault # Password of `tsuper` and `ffmpeg`
      # Solr
      SOLR_ADMIN_PASSWORD: MediaVault # Password of `solr` user via Nginx proxy


  postgres:
    environment:
      <<: *default_environment

  solr:
    environment:
      <<: *default_environment

  ffmpeg:
    environment:
      <<: *default_environment

  nginx-for-repository:
    environment:
      <<: *default_environment
      SSL_CERTIFICATE: |
        # Generate localhost.pem via /docker/nginx-for-proxy/ssl/README.md and paste its contents here
      SSL_CERTIFICATE_KEY: |
        # Generate localhost.key via /docker/nginx-for-proxy/ssl/README.md and paste its contents here
      SSL_DHPARAM: |
        # Generate dhparam.pem via /docker/nginx-for-proxy/ssl/README.md and paste its contents here

  opentext-directory-services:
    environment:
      <<: *default_environment

  opentext-media-management-core-app:
    environment:
      <<: *default_environment

  opentext-media-management-indexer:
    environment:
      <<: *default_environment

  nginx-for-proxy:
    environment:
      <<: *default_environment

  maildev:
    environment:
      <<: *default_environment
